on: [push, workflow_dispatch]
name: Building

jobs:
  building:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Compile the mod
        run: |
          chmod +x gradlew
          ./gradlew release --debug
        
      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-zipped
          path: mod-src/build/libs/ui-debugger-any-platform.jar
        
